server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
